version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: 'Dockerfile'
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 512M # Batasi penggunaan memori hingga 512 MB
        depends_on:
            - mysql
        environment:
            APP_DEBUG: 'false'
            CASHIER_MACHINE_FRONTEND: 'http://localhost:5173'
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: 'root' # Password untuk user root MySQL
            DB_NAME: machine-cashier
        env_file:
            - ./backend/.env
        ports:
            - '3000:3000'
        volumes:
            - ./backend:/app
        networks:
            - cashier-network

    mysql:
        image: mysql:8.0-debian # Menggunakan image MySQL versi 8.0-debian
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root # Password untuk user root MySQL
            MYSQL_DATABASE: machine-cashier
            MYSQL_USER: user # User untuk koneksi ke database
            MYSQL_PASSWORD: password # Password untuk user 'user'
        ports:
            - '3306:3306'
        volumes:
            - ./my.cnf:/etc/mysql/my.cnf # Menggunakan konfigurasi MySQL
            - mysql_data:/var/lib/mysql # Volume untuk persistensi data MySQL
        networks:
            - cashier-network

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysql # Mengarah ke service MySQL
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '8080:80'
        depends_on:
            - mysql
        networks:
            - cashier-network

volumes:
    mysql_data: {} # Volume untuk data MySQL

networks:
    cashier-network:
        driver: bridge # Jaringan bridge untuk komunikasi antar container
