version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: 'Dockerfile'
        depends_on:
            - mysql
        environment:
            APP_DEBUG: 'false'
            CASHIER_MACHINE_FRONTEND: 'http://localhost:5173'
            DB_HOST: mysql
            DB_USER: root
            DB_PASS: 'root' # Password for MySQL root user
            DB_NAME: machine-cashier
        env_file:
            - ./backend/.env
        ports:
            - '3000:3000'
        volumes:
            - ./backend:/app
        networks:
            - cashier-network

    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root # Root password
            MYSQL_DATABASE: machine-cashier
            MYSQL_USER: user # Optional user for connecting
            MYSQL_PASSWORD: password # Password for 'user'
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - cashier-network

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysql # This points to the MySQL service
            PMA_USER: root # Using root for phpMyAdmin login
            PMA_PASSWORD: root # This password should match MYSQL_ROOT_PASSWORD
        ports:
            - '8080:80'
        depends_on:
            - mysql
        networks:
            - cashier-network

volumes:
    mysql_data: {} # Named volume for MySQL data persistence

networks:
    cashier-network:
        driver: bridge # Use bridge network for inter-container communication
